"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { FileAudio, LoaderCircle, Plus, RefreshCw, Trash2, UploadCloud } from "lucide-react";
import { api, upload, type Meeting } from "@/lib/api";
import { Button } from "@/components/ui/button"; import { Card, CardContent } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Badge } from "@/components/ui/badge";

const labels: Record<string,string> = {uploaded:"等待处理",transcribing:"正在转写",summarizing:"生成总结",completed:"已完成",failed:"处理失败"};
export default function MeetingsPage(){ const [items,setItems]=useState<Meeting[]>([]); const [title,setTitle]=useState(""); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const load=useCallback(()=>api<Meeting[]>("/meetings").then(setItems).catch(e=>setError(e.message)),[]); useEffect(()=>{load(); const timer=setInterval(load,5000); return()=>clearInterval(timer)},[load]);
  async function submit(e:FormEvent){e.preventDefault(); if(!file)return; setBusy(true);setError("");const form=new FormData();form.append("title",title);form.append("file",file);try{await upload<Meeting>("/meetings",form);setTitle("");setFile(null);await load()}catch(e){setError(e instanceof Error?e.message:"上传失败")}finally{setBusy(false)}}
  async function remove(id:string){await api(`/meetings/${id}`,{method:"DELETE"});load()}
  return <div className="mx-auto max-w-6xl space-y-6"><div><p className="text-sm font-semibold text-indigo-600">会议智能</p><h1 className="mt-1 text-3xl font-bold">会议中心</h1><p className="mt-2 text-sm text-slate-500">上传录音，自动完成转写、总结、决策与待办提取。</p></div><Card className="shadow-none"><CardContent className="p-5"><form onSubmit={submit} className="grid gap-3 md:grid-cols-[1fr_1.4fr_auto]"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="会议标题" required /><label className="flex h-11 cursor-pointer items-center gap-2 rounded-lg border bg-white px-3 text-sm text-slate-500"><UploadCloud className="size-4" /><span className="truncate">{file?.name??"选择音频文件"}</span><input className="hidden" type="file" accept="audio/*" onChange={e=>setFile(e.target.files?.[0]??null)} required /></label><Button disabled={busy||!file}>{busy?<LoaderCircle className="size-4 animate-spin"/>:<Plus className="size-4"/>}{busy?"上传中":"上传并处理"}</Button></form>{error&&<p className="mt-3 text-sm text-rose-600">{error}</p>}</CardContent></Card><div className="space-y-3">{items.length===0&&<div className="rounded-xl border border-dashed bg-white p-12 text-center text-sm text-slate-400">还没有会议录音，上传第一条开始使用。</div>}{items.map(item=><Card key={item.id} className="shadow-none"><CardContent className="p-5"><div className="flex items-start gap-4"><div className="grid size-11 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><FileAudio className="size-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{item.title}</h2><Badge className={item.status==="completed"?"bg-emerald-50 text-emerald-600":item.status==="failed"?"bg-rose-50 text-rose-600":"bg-amber-50 text-amber-600"}>{labels[item.status]??item.status}</Badge></div><p className="mt-1 text-xs text-slate-400">{item.filename} · {new Date(item.created_at).toLocaleString("zh-CN")}</p>{item.transcript&&<details className="mt-4 rounded-lg bg-slate-50 p-3"><summary className="cursor-pointer text-sm font-medium">查看转写</summary><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{item.transcript}</p></details>}{item.summary&&<div className="mt-4 rounded-lg border border-indigo-100 bg-indigo-50/50 p-4"><p className="text-sm font-semibold text-indigo-900">AI 会议总结</p><p className="mt-2 text-sm leading-6 text-slate-600">{String(item.summary.overview??"")}</p>{Array.isArray(item.summary.key_points)&&<ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{(item.summary.key_points as string[]).map(x=><li key={x}>{x}</li>)}</ul>}</div>}</div><Button variant="ghost" size="icon" onClick={()=>remove(item.id)} aria-label="删除会议"><Trash2 className="size-4 text-slate-400"/></Button></div></CardContent></Card>)}</div><Button variant="outline" onClick={load}><RefreshCw className="size-4"/>刷新状态</Button></div> }
